### ISSUE TITLE
Add root element to quest language

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#100]
Add a root `<quest>` element with metadata (time estimate, title, synopsis, number of players, credits, version number, companion resources)

**Comment by toddmedema** [comment]
Proposed initial metadata:
- title (string, required, max length ~ 40 characters)
- pitch (string, required, max length ~ a tweet / 140 characters)
- summary (string, optional, max length ~ a paragraph / 800 characters)
- credits
  - author (can have multiple; in order of importance)
    - name (string)
    - url (string)
- recommendedMinimumPlayers (int, optional)
- recommendedMaximumPlayers (int, optional)
- estimatedMinimumMinutes (int, required)
- estimatedMaximumMinutes (int, required)


Other ideas / v2:
- id (so that changing the name doesn't break references to the quest - auto-assigned integer?)
- version number (quest source control? what does the editing interface look like for authors?)
- companion resources (array of files used; could be auto-generated by scanning through the quest for file references. Could alternatively bundle all of the quest's resources in a folder (ie `/id`))
- tags (array of strings, optional) - we'd need to create a list of flags, things like fantasy, scifi, comedy, family-friendly (heck, we could even just use movie genres as a starting point)
