### ISSUE TITLE
Write FAQ for main site

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#181]
We should keep track of user questions, merge the common ones, and put it on our website somewhere.

**Comment by toddmedema** [comment]
Makes sense. Was thinking of perhaps integrating this into the rules? Questions I've gotten so far:

- how do abilities like Signal Shot work? "All damage enemies would deal you this round (before reductions) is instead dealt to the target". We can explain that you have to jump ahead in the app to see how much damage you'll take, then jump back to the tier count screen to update it if you kill any enemies. **thinking that we might just want a section explaining difficult cards**
- what happens when adventurers die? They cannot play abilities or loot for the rest of combat. At the end of combat, they are revived to the same health as the rest of the party (full health, unless otherwise specified)

**Comment by toddmedema** [comment]
Added here, thoughts? https://www.expeditiongame.com/begin

**Comment by smartin015** [comment]
"d20 dice" -> "d20 die"

Could probably put the "how to play" video above all the other text for better balance. 

"Quest!" Section should mention handing off the app for each person to read.

Under specific cards section:

```
Some cards have more complex rules. Here's some clarifications:
```

Then mention reporting other issues at the end.

There's an extra quotation under "Desperation" card clarification

Give And Take: "knocked out until the rest of the fight, or until healed"

Dead clarification doesn't mention re-healing during combat.

**Comment by toddmedema** [comment]
@smartin015 good points, updated!

**Comment by smartin015** [comment]
A few last comments:

* Any way we could remove that large padding at the top of the video and make it match the side padding?
* Learn to play section requirements could probably be bulleted for easier reading
* "Choose a game mode" lists Guided Adventure as something we have, but AFAIK we don't have that any more.
* Solo play player setup section... mention discarding the remaining two drawn cards.
* Under Loot and Learn: "All Loot is one-time-use" is false. Also, the repetition of numbers in parentheses is kind of weird IMO.

Otherwise, LGTM.

**Comment by toddmedema** [comment]
1. reduced it a bit. Note that that padding is defined for all pages, ie including the homepage. Think it also felt off because there was no page title, just BAM video, so tried putting a title there. Let me know if you think it's better or worse
2. updated
3. cleaned up game mode section
4. Added
5. cleaned up the loot section

**Comment by smartin015** [comment]
Looks good. Leading characters on the first set of bullets should probs be capitalized though.

"Adventurers may also choose to discard and learn a new ability"... this makes it sound as though ability picking can be done at the end of *every* encounter. Maybe say that this is indicated by the app?

**Comment by toddmedema** [comment]
Updated! (if that all looks good, feel free to close the issue)
