### ISSUE TITLE
Combat without Rewards

### ISSUE THREAD

**Issue by wls** [Fabricate-IO/expedition-app#76]
Ran into another edge-case in crafting a quest.  We're trying to engage in combat where we don't want a reward (loot) after an encounter.  Need a way to suppress that.

The _reason_ is that we're trying to alter the state of what happens -- such as lifting a key off someone, getting a relevant quest item, taking something from someone who has little to no items to drop as rewards.  e.g., it makes no sense to take down a beggar or a monk and have a pile of loot given to the party in the context of the story.

**Comment by smartin015** [comment]
This sounds like an extra attribute to the encounter, maybe `loot="false"`, where it defaults to true unless specified.

**Comment by wls** [comment]
Having a `loot="false"` option would be solve the problem elegantly. Would it be possible to also address not leveling up.  (We're working on a quest where the party gets away, but doesn't deserve a reward.)

**Comment by toddmedema** [comment]
@smartin015 this seems like it's worth considering along with the other new combat metadata we're thinking of

**Comment by smartin015** [comment]
Agreed. Turning off loot and level increases would be useful for quest creators.

**Comment by toddmedema** [comment]
Even better: generically allowing creators to define custom loot and level increase information. IE you could set levelup=0, 1, 2, or you could set loot=false or {1:2, 2:1, 3:1}

**Comment by smartin015** [comment]
Sure, why the hell not :D

Dunno what that'd look like in QDL though, apart from an extra json blob at the end. Maybe we should keep it that way.

**Comment by toddmedema** [comment]
Thought here from writing a quest - allowing combat w/o rewards would allow quest creators to remove the current final combat awkwardness (aka drawing new loot and abilities, just to have the quest end)

If that's the case, it might be useful to have a shorthand for combat with no rewards, so that creators aren't trying to remember / type out huge JSON objects for any combat whose victory ends the quest (admittedly, would usually only happen once, maybe twice per quest, but still annoying)

**Comment by smartin015** [comment]
A few options:

Could use the next-line attribute style as in the quest header, e.g. 

```
_combat_
loot: false
levelUp: false
```

We could make them ops and assignable in the combat node:

```
_combat_

{{loot=false; levelUp=false;}}
```

but that runs into scoping issues. We could add additional tags after the combat header:

```
_combat_ (#id) [no_loot, no_level]
```

Or we could make a new form of combat tag:

```
_norewardcombat_
```

None of these seem particularly 'clean'. What about:

```
_combat_

* on loot
  
  **goto next**
```

Where we could reserve the "next" word? Overriding the default card feels a lot more principled to me. Maybe we should work out some way of more succinctly indicating an event is "suppressed" so it's just skipped.

**Comment by toddmedema** [comment]
I do like the `* on loot` idea - perhaps `* on reward` would be better? Certainly opens it up to more possibilities from creators.

Wouldn't we not need to add `**goto next**`, since that's the default?

**Comment by smartin015** [comment]
As per discussion... `**goto next**` or something like `**next**` to skip the existing card, otherwise card is completely overridden.

**Comment by toddmedema** [comment]
Writing a quest right now, found another use for `**next**`:

```
_title_

text

* choice one 

  unique text, that then falls through

* choice two
 
  // really just want this to fallthrough without any additional text, but without **goto next** would have to assign a custom ID to the next node

Text to fall through to
```

For example, if you kill some people and could bury their bodies and move on, or just move on

**Comment by toddmedema** [comment]
Had a thought here. There are really three separate parts of post-combat to customize:

- healing
- loot
- leveling up

And there are times when you want to just edit one, or two, of the three - but keep the default behavior for the others.

Also, thinking about the far future of the app (ie multiple types of apps, say one that can be played entirely on your computer), it's more useful to have programmatic definitions for everything (ie heal 2 health, draw 1 tier 2 loot), rather than letting quest creators insert arbitrary text (which they can do on the `*on win` page anyway.

To that end, I think the metadata format would be the most flexible, but also best for the future:

```
_combat_
loot: false
levelUp: false // note, maybe we don't add levelUp just quite yet, since we're also talking about adding XP / a more useful level-up strategy
heal: 2
```

@smartin015 @wls thoughts?

**Comment by smartin015** [comment]
I think an easier step before this is to make it available via JSON:

```
_combat_ {"loot": false, "levelUp": false, "heal": 2}
```

This is similar effort, already done, and doesn't require additional syntax.
